### ISSUE TITLE
Version 1.4 import does not allow numeric fields as sku

### ISSUE THREAD

**Issue by s0ps** [akeneo-labs/ExcelConnectorBundle#12]
Import fails if sku field is numeric: 
Error:
PIM_EXCEL_CONNECTOR.JOBS.PRODUCT.IMPORT.TITLE  Attribute or field "sku" expects a string as data, "integer" given (for filter string).

**Comment by antoineguigan** [comment]
Hi s0ps,

We are looking in this matter, and will be coming shortly towards you.

Antoine

**Comment by damien-carcel** [comment]
This has been fixed both for Akeneo 1.3 (ExcelConnectorBundle 1.4.1) and 1.4 (ExcelConnectorBundle 1.5.1).

Regards,
Damien
