### ISSUE TITLE
It's not working on Akeneo 1.4

### ISSUE THREAD

**Issue by manh-nguyen** [akeneo-labs/ExcelConnectorBundle#21]
Hi guys,

Please make it available for Akeneo 1.4. This is very important bundle for us.

Thank you very much !

Regards,
Manh - Balance Internet

**Comment by damien-carcel** [comment]
Hi Manh.

We are working to release a 1.5 version. It should be available by the end of the week.

Regards,
Damien

**Comment by marcobamert** [comment]
Hi Damien

I've tried to install the bundle with the latest 1.5.0 release. Unfortunately, I get another error:

```
PHP Fatal error:  Class 'Oro\\Bundle\\LocaleBundle\\EventListener\\LocaleListener' not found in /var/www/host/app/cache/prod/classes.php on line 2725
PHP Stack trace:
PHP   1. {main}() /var/www/host/web/app.php:0
PHP   2. Symfony\\Component\\HttpKernel\\Kernel->handle() /var/www/host/web/app.php:24
PHP   3. Symfony\\Component\\HttpKernel\\Kernel->getHttpKernel() /var/www/host/app/bootstrap.php.cache:2428
PHP   4. Symfony\\Component\\DependencyInjection\\Container->get() /var/www/host/app/bootstrap.php.cache:2432
PHP   5. appProdProjectContainer->getHttpKernelService() /var/www/host/app/bootstrap.php.cache:2139
PHP   6. Symfony\\Component\\DependencyInjection\\Container->get() /var/www/host/app/cache/prod/appProdProjectContainer.php:2375
PHP   7. appProdProjectContainer->getEventDispatcherService() /var/www/host/app/bootstrap.php.cache:2139
PHP   8. Symfony\\Component\\EventDispatcher\\ContainerAwareEventDispatcher->addSubscriberService() /var/www/host/app/cache/prod/appProdProjectContainer.php:2025
```

**Comment by damien-carcel** [comment]
Hello Marco.

Did you completely clear your cache?
"rm -rf app/cache/* && app/console cache:clear --env=prod"

@manh-nguyen The version 1.5 of the ExcelConnectorBundle is now released. You can use it with Akeneo 1.4.

Regards,
Damien

**Comment by marcobamert** [comment]
Hi Damien

Clearing the cache itself didn't help for some strange reasons - however after a complete rebuild of the project the error is gone.

Thanks
Marco

**Comment by manh-nguyen** [comment]
Hi @damien-carcel , Thank you very much for the upgrade!
I could install it as well now and also ran the excel import successfully.
But look like something wrong with the validation:
{quote}
PIM_EXCEL_CONNECTOR.STEPS.TRANSFORMER_PROCESSOR.TITLE 
code: Option code may contain only letters (at least one), numbers and underscores
Hide item
attribute:		 baud_ratebps_ss
code	: 		19200
label-en_AU:	19200
{quote}

**Comment by phaseinducer** [comment]
Hi Manh,

This restriction on full numeric codes has been added in Akeneo 1.4 but the core team is working right now on reverting it. The next release should solve your problem.

Regards,
Yohan

**Comment by manh-nguyen** [comment]
Wait you guys result :)

**Comment by sagikazarmark** [comment]
It is still not working form me (latest akeneo and excel connector):

`PHP Fatal error:  Call to a member function getCode() on a non-object in /Users/mark/Projects/Freelance/Allround/creatools-pim/vendor/akeneo/pim-community-dev/src/Pim/Bundle/CatalogBundle/Entity/AttributeRequirement.php on line 114`

**Comment by damien-carcel** [comment]
Hi.

This could be a bug related to the Excel connector. We will investigate it and come back to you as soon as possible.

Regards,
Damien

**Comment by sagikazarmark** [comment]
Hi @damien-carcel 

Thanks! I started to investigate the issue, but I gave it up. I found that for some reasons the family does not have a channel, that's why the method is called on a non-object.

**Comment by damien-carcel** [comment]
@manh-nguyen The PIM has been tagged 1.4.3 with the fix for full numeric entity codes. It should work for you now.

@sagikazarmark Could you tell me what export / manipulation you were doing exactly, so I can try to reproduce it.

Regards to both of you
Damien

**Comment by sagikazarmark** [comment]
@damien-carcel I can send you the file privately of you want.

**Comment by damien-carcel** [comment]
Hello @sagikazarmark, sorry I wasn't able to come back to you sooner.

It would probably not work if it is a product import, as I will not have the same catalog structure than you. And if the problem appears during an init import, then the problem is in your file, where you need to add channel(s) to the family.

If the problem is with product import, you can try something: export your excel file in CSV, and try the import with the Akeneo standard CSV connector. From what you describes, I suspect this is a problem in the PIM, not specific to the ExcelConnectorBundle (as the excel connector uses the same elements than the CSV connector for writing imports).

Regards,
Damien
