### ISSUE TITLE
Sample excel file for XLSX Product import

### ISSUE THREAD

**Issue by manh-nguyen** [akeneo-labs/ExcelConnectorBundle#30]
Hi Akeneo team,

As Laure (Helpdesk team) said, we can import products using excel connector. I'm interested in to know the excel file format for it.

How is it working with multiple sheets?
Can you provide me a sample file of excel for product import? That would be good to have a sample file for multiple sheets.

Thanks guys !
Cheers,
Manh

**Comment by manh-nguyen** [comment]
Actually I got this sample file by exporting products using excel connector. But it has only 1 sheet and it looks very similar to csv file format. 
Is it possible to has multiple sheets in excel file?
If it does, please send me the sample file with multiple sheets.

Cheers,
Manh

**Comment by LaureBro** [comment]
Hi Manh, 

Me again ;) Here is an example of a init.xlsx file.
This file allows you to import multiple sheets at once, you will find all details in the file itself.
[InitFileExample.xlsx](https://github.com/akeneo-labs/ExcelConnectorBundle/files/45112/InitFileExample.xlsx)

Best regards, 

Laure

**Comment by manh-nguyen** [comment]
:D Hi @LaureBro ,

It's an init catalog structure excel file. I'm talking about XLSX Product import file. But I already got this file. excel connector doesn't care about name or number of sheet in excel file, just the row format look the same as csv product import file.

Regards,
Manh
