### ISSUE TITLE
 [ErrorException] Array to string conversion

### ISSUE THREAD

**Issue by VasyaChernets** [akeneo-labs/ExcelConnectorBundle#36]
Hello dear akeneo-labs.
i have a little trouble with install "ExcelConnectorBundle"
i use terminal paste "php composer.phar require --prefer-dist akeneo-labs/excel-connector-bundle:1.5.*"
and after that i see message : "please define your magento root dir [root]" i write my path and see this error "[ErrorException] to string conversion " 
![screenshot from 2016-03-02 19-01-01](https://cloud.githubusercontent.com/assets/15193807/13467961/35b54036-e0a9-11e5-8462-a47637341062.png)
can you help me , please?

**Comment by fitn** [comment]
Hi @VasyaChernets 

Could you give me more details about this error? The fact to define the `magento root dir` has no link with the ExcelConnectorBundle.

Regards,

**Comment by VasyaChernets** [comment]
Hello @fitn 
I apologize connector well established.
it's my falt,that I didn't understand is how to use him.

**Comment by mdamaceno** [comment]
@VasyaChernets could you show me how you fix that?
