### ISSUE TITLE
Zero-Length Keys while Product Import

### ISSUE THREAD

**Issue by McSurf84** [akeneo-labs/ExcelConnectorBundle#40]
Hello everybody,

I´m using Akeneo 1.4 with MongoDB 2.4.14. When I export all my products into a xlsx file and try to reimport them I´ll get the following error:
`{"id":"zero-length keys are not allowed, did you use $ with double quotes?","domain":"messages","locale":"en"}`

It is possible to configure MongoDB to accept zero length keys, but from my experience it can lead to data failure or misbehaviour.

Is there any way to prevent from this error?

**Comment by fitn** [comment]
Hi @McSurf84 

This error seems coming from Akeneo PIM version. Please, try to upgrade to the 1.4.21.
I can not reproduce with your file.

Regards,
