### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by navyon** [akeneo-labs/ExcelConnectorBundle#53]
After installing this bundle and following the instructions, Akeneo has stopped working.

**Comment by fitn** [comment]
Hi @navyon 

Could you give more information about your problem?!

What do you mean by "Akeneo has stopped working"? Could you try it in dev mode? Do you have any log information in `app/logs/` ?

Regards,

**Comment by navyon** [comment]
Hello,

After installing the bundle I got a 500 http error.  I've also noticed there are some issues with my installation, the last log entry was about 1 month ago, so I am not sure how I can re-enable the logs.  When I would go to the dev environment it says that your not allowed access to this file check my app_dev.php.

Regards,

**Comment by jmleroux** [comment]
Hello @navyon ,

to use the dev environment, you have to modify `app_dev.php` following this comment : https://github.com/akeneo/pim-community-standard/blob/1.5/web/app_dev.php#L10

You could for example add your IP in the list of allowed IPs here : https://github.com/akeneo/pim-community-standard/blob/1.5/web/app_dev.php#L14

And as always with Symfony, do not forget to clear your cache after vendor modifications ;)

Regards,
JM

**Comment by navyon** [comment]
@jmleroux Thanks for your reply, I did a rollback of my vm to a working state.  And because of your comment I was able to get my dev environment running again.   I would like to try to install the Excel connector bundle again, is it possible to install it only in the Dev environment ?  Or should I create a seperate VM to test it ?

**Comment by jmleroux** [comment]
I didn't try to install it only in dev, but if you register it [here](https://github.com/akeneo/pim-community-standard/blob/1.5/app/AppKernel.php#L26), it will be active only in dev mode.

**Comment by navyon** [comment]
@jmleroux Oke I am a step further, I have managed to install the connector on a second vm, I dont see the import option in the UI, or in the list of import jobs.

**Comment by jmleroux** [comment]
@navyon ,

firstly, could you explain why you need this module? It seems you already have a working Akeneo and this extension is only for initialization.

**Comment by navyon** [comment]
@jmleroux Yes I do, have a working Akeneo, however the products are not loaded as yet, I am still at the stage where we are cleaning and preparing the data. I wanted to see if this was a solution to import everything. But I think I may have to stick to the CSV import.

**Comment by jmleroux** [comment]
So you are in the right place :+1: 

This is indeed a solution we made to import everything
